# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connstats.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='connstats.proto',
  package='connstatsprotobuf',
  syntax='proto3',
  serialized_options=b'Z!ConnectionStats/connstatsprotobuf',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63onnstats.proto\x12\x11\x63onnstatsprotobuf\"\xbe\x01\n\x0e\x43onnectionStat\x12\x10\n\x08protocol\x18\x01 \x01(\t\x12\x0c\n\x04l_ip\x18\x02 \x01(\t\x12\x0c\n\x04r_ip\x18\x03 \x01(\t\x12\x0e\n\x06l_port\x18\x04 \x01(\r\x12\x0e\n\x06r_port\x18\x05 \x01(\r\x12\r\n\x05inpps\x18\x06 \x01(\x04\x12\x0e\n\x06outpps\x18\x07 \x01(\x04\x12\r\n\x05inbpp\x18\x08 \x01(\x04\x12\x0e\n\x06outbpp\x18\t \x01(\x04\x12\x0f\n\x07inboutb\x18\n \x01(\x04\x12\x0f\n\x07inpoutp\x18\x0b \x01(\x04\"\x0e\n\x0cStatsRequest\"A\n\nStatsReply\x12\x33\n\x08\x63onnstat\x18\x01 \x03(\x0b\x32!.connstatsprotobuf.ConnectionStat2`\n\x0cStatsService\x12P\n\x0c\x43ollectStats\x12\x1f.connstatsprotobuf.StatsRequest\x1a\x1d.connstatsprotobuf.StatsReply\"\x00\x42#Z!ConnectionStats/connstatsprotobufb\x06proto3'
)




_CONNECTIONSTAT = _descriptor.Descriptor(
  name='ConnectionStat',
  full_name='connstatsprotobuf.ConnectionStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol', full_name='connstatsprotobuf.ConnectionStat.protocol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l_ip', full_name='connstatsprotobuf.ConnectionStat.l_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r_ip', full_name='connstatsprotobuf.ConnectionStat.r_ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l_port', full_name='connstatsprotobuf.ConnectionStat.l_port', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r_port', full_name='connstatsprotobuf.ConnectionStat.r_port', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inpps', full_name='connstatsprotobuf.ConnectionStat.inpps', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outpps', full_name='connstatsprotobuf.ConnectionStat.outpps', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inbpp', full_name='connstatsprotobuf.ConnectionStat.inbpp', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outbpp', full_name='connstatsprotobuf.ConnectionStat.outbpp', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inboutb', full_name='connstatsprotobuf.ConnectionStat.inboutb', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inpoutp', full_name='connstatsprotobuf.ConnectionStat.inpoutp', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=229,
)


_STATSREQUEST = _descriptor.Descriptor(
  name='StatsRequest',
  full_name='connstatsprotobuf.StatsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=245,
)


_STATSREPLY = _descriptor.Descriptor(
  name='StatsReply',
  full_name='connstatsprotobuf.StatsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='connstat', full_name='connstatsprotobuf.StatsReply.connstat', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=312,
)

_STATSREPLY.fields_by_name['connstat'].message_type = _CONNECTIONSTAT
DESCRIPTOR.message_types_by_name['ConnectionStat'] = _CONNECTIONSTAT
DESCRIPTOR.message_types_by_name['StatsRequest'] = _STATSREQUEST
DESCRIPTOR.message_types_by_name['StatsReply'] = _STATSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectionStat = _reflection.GeneratedProtocolMessageType('ConnectionStat', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONSTAT,
  '__module__' : 'connstats_pb2'
  # @@protoc_insertion_point(class_scope:connstatsprotobuf.ConnectionStat)
  })
_sym_db.RegisterMessage(ConnectionStat)

StatsRequest = _reflection.GeneratedProtocolMessageType('StatsRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATSREQUEST,
  '__module__' : 'connstats_pb2'
  # @@protoc_insertion_point(class_scope:connstatsprotobuf.StatsRequest)
  })
_sym_db.RegisterMessage(StatsRequest)

StatsReply = _reflection.GeneratedProtocolMessageType('StatsReply', (_message.Message,), {
  'DESCRIPTOR' : _STATSREPLY,
  '__module__' : 'connstats_pb2'
  # @@protoc_insertion_point(class_scope:connstatsprotobuf.StatsReply)
  })
_sym_db.RegisterMessage(StatsReply)


DESCRIPTOR._options = None

_STATSSERVICE = _descriptor.ServiceDescriptor(
  name='StatsService',
  full_name='connstatsprotobuf.StatsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=314,
  serialized_end=410,
  methods=[
  _descriptor.MethodDescriptor(
    name='CollectStats',
    full_name='connstatsprotobuf.StatsService.CollectStats',
    index=0,
    containing_service=None,
    input_type=_STATSREQUEST,
    output_type=_STATSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATSSERVICE)

DESCRIPTOR.services_by_name['StatsService'] = _STATSSERVICE

# @@protoc_insertion_point(module_scope)
